Update arm gcc to 8.3.1
qmk/qmk_base_container pull request #7
Opened 2019-11-07 19:57 UTC by zvecr

2020-03-07 06:50 UTC, skullydazed approved these changes

2020-03-07 09:12 UTC, fauxpark approved these changes

2020-09-11 20:26 UTC, fauxpark requested changes
`libnewlib-arm-none-eabi` should also be removed, I think.

2021-02-10 04:07 UTC, fauxpark approved these changes

2021-02-10 19:50 UTC, drashna approved these changes

2022-01-31 02:08 UTC, zvecr commented
debian 11 ships with 8.3.1 so for now this is no longer required

2022-01-31 02:08 UTC, closed without merging